sudo: required
language: generic

services:
 - docker

before _install:
  -docker build -t moaz-adel/react-test -f Dockerfile.dev .

scripts:

  -docker run -e CI=true moaz-adel/react-test npm run test 